# PostgreSQL統一設定
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mvp_development
  host: db
  username: postgres
  password: password

test:
  <<: *default
  database: mvp_test
  host: db
  username: postgres
  password: password

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    migrations_paths: db/cable_migrate
  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    migrations_paths: db/queue_migrate